# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test_abz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test_abz

	pod 'Alamofire'

end
